[profile.default]
src = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
# Add remapping for suzaku core
remappings = ["@suzaku/core=lib/suzaku-core/"]

[rpc_endpoints]
localhost = "http://localhost:8545"
fuji = "${FUJI_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
fuji = { key = "${ETHERSCAN_API_KEY}" }
avalanche = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" } 
