[profile.default]
src = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.dev]
optimizer = false
sparse_mode = true

[rpc_endpoints]
localhost = "http://localhost:8545"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
avalanche = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=43114" }
fuji = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=43113" }
