[profile.default]
src = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
localhost = "http://localhost:8545"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}" }
avalanche = { key = "${SNOWTRACE_API_KEY}" }
sepolia = { key = "${SNOWTRACE_API_KEY}" }
ethereum = { key = "${SNOWTRACE_API_KEY}" } 
